/*!
 * MXpert Chat loader (Subresource Integrity shim)
 * ------------------------------------------------
 * This tiny script is what customer websites embed. It never changes between
 * widget releases, so a site only ever pastes it in ONCE.
 *
 * On each release our CI bakes the current widget's content-addressed filename
 * and its SRI hash into the block below. The browser then verifies the widget
 * bytes against that hash before executing them, so a tampered widget file is
 * rejected automatically.
 *
 * This file is intentionally NOT minified or obfuscated so anyone (including a
 * security reviewer) can read exactly what it does. Do NOT hand-edit the
 * published copy — it is generated by scripts/build-loader.mjs.
 */
(function () {
  "use strict";

  // ---- BEGIN generated release manifest (do not edit by hand) ----
  var BASE = "https://cdn.jsdelivr.net/gh/MechMonkey/Mxpert-Chat@staging/";
  var ASSETS = {
  "index": {
    "file": "widget/index.2b74b32c1b68.js",
    "integrity": "sha384-Hz2I/FsIy7JG/iFqsZ5lZ8gzuiXhothshujxyRQzVZhixVoE/tuySXNhSMxVP/nz"
  },
  "full-page": {
    "file": "widget/full-page.cdb1185e8454.js",
    "integrity": "sha384-Fymx9y0v2lnogOQjkghj/8KqhndkXdL89pwAVZ0LmYXUu0/MHEqukxCQAAXK/yJY"
  }
};
  // ---- END generated release manifest ----

  if (window.__mxpertLoaderInit) return;
  window.__mxpertLoaderInit = true;

  // Locate this loader's own <script> tag so we can read its data-* config.
  var self = document.currentScript;
  if (!self) {
    var candidates = document.querySelectorAll('script[src*="loader.js"]');
    self = candidates[candidates.length - 1] || null;
  }
  if (!self) {
    if (window.console && console.error) {
      console.error(
        "[MXpert] loader could not find its own <script> tag. " +
          "Use a classic <script> (not type=module)."
      );
    }
    return;
  }

  var entry = (self.getAttribute("data-entry") || "index").toLowerCase();
  var asset = ASSETS[entry] || ASSETS.index;
  if (!asset) return;

  var s = document.createElement("script");
  s.src = BASE + asset.file;
  s.integrity = asset.integrity; // browser refuses to run mismatched bytes
  s.crossOrigin = "anonymous"; // required for SRI on a cross-origin CDN
  s.async = self.async;
  s.defer = self.defer;

  // Forward the customer's configuration (data-site, data-api, data-theme, ...)
  // to the real widget script. We strip attributes that are ours to control.
  var skip = {
    src: 1,
    integrity: 1,
    crossorigin: 1,
    "data-entry": 1,
    type: 1,
  };
  for (var i = 0; i < self.attributes.length; i++) {
    var a = self.attributes[i];
    if (skip[a.name.toLowerCase()]) continue;
    s.setAttribute(a.name, a.value);
  }

  // Marker the widget uses to recover its config, because document.currentScript
  // is null for dynamically-injected scripts.
  s.setAttribute("data-mxpert-widget", entry);

  (self.parentNode || document.head || document.documentElement).insertBefore(
    s,
    self.nextSibling
  );
})();
